In [28]:
import pandas as pd

The direct matching dataset contains the best 10 candidates for each job position.

In [29]:
dm_df = pd.read_csv('direct_matching_20240213_eng.csv', encoding='Windows-1252', sep = ';')

In [30]:
dm_df.head()

,cand_id,job_id,distance_km,match_score,match_rank,cand_gender,cand_age_bucket,cand_domicile_province,cand_domicile_region,cand_education,job_contract_type,job_professional_category,job_sector,job_work_province
0,"5,664,912",OFF_1011_1427,3.232.704.163,9.957.338.715,1,Male,45-54,UD,FRIULI VENEZIA GIULIA,NaN,Subordinate employment,Surveying and technician of civil and industri...,Designers / Design / Graphics,UD
1,"4,999,120",OFF_1011_1427,155.955.925,9.921.056.366,2,Male,35-44,UD,FRIULI VENEZIA GIULIA,NaN,Subordinate employment,Surveying and technician of civil and industri...,Designers / Design / Graphics,UD
2,"5,413,671",OFF_1011_1427,3.134.887.695,991.186.142,3,Female,45-54,UD,FRIULI VENEZIA GIULIA,NaN,Subordinate employment,Surveying and technician of civil and industri...,Designers / Design / Graphics,UD
3,"5,965,090",OFF_1011_1427,6.631.559.753,9.740.976.715,4,Male,15-24,TS,FRIULI VENEZIA GIULIA,NaN,Subordinate employment,Surveying and technician of civil and industri...,Designers / Design / Graphics,UD
4,"5,771,219",OFF_1011_1427,155.955.925,9.732.387.543,5,Female,35-44,UD,FRIULI VENEZIA GIULIA,NaN,Subordinate employment,Surveying and technician of civil and industri...,Designers / Design / Graphics,UD

The reverse matching dataset contains the best 5 offers (job positions published on Adecco website) and the best 5 orders (job position managed internally without publishing on Adecco website) for each candidate

In [31]:
rm_df = pd.read_csv('reverse_matching_20240213_eng.csv', encoding='Windows-1252', sep=';')

In [32]:
rm_df.head()

,cand_id,job_id,distance_km,match_score,match_rank,cand_gender,cand_age_bucket,cand_domicile_province,cand_domicile_region,cand_education,job_contract_type,job_professional_category,job_sector,job_work_province
0,"11,208",OFF_3435_4864,30.609745,99.309860,1,Female,25-34,VE,VENETO,"Master's Degree: Economics for arts, culture a...",Search and selection,secretary/secretary,Secretariat / General Services,TV
1,"11,208",ORD_13361_0218,42.466312,96.529259,1,Female,25-34,VE,VENETO,"Master's Degree: Economics for arts, culture a...",Subordinate employment,Employee (m/f),Secretariat / General Services,PN
2,"11,208",ORD_14183_0606,33.240650,95.374954,2,Female,25-34,VE,VENETO,"Master's Degree: Economics for arts, culture a...",Subordinate employment,Human Resources Officer (m/f),Human Resources / Recruitment,TV
3,"11,208",OFF_635_0402,58.744339,94.199844,2,Female,25-34,VE,VENETO,"Master's Degree: Economics for arts, culture a...",Search and selection,Telemarketing operator,Call Center / Customer Care,PD
4,"11,208",OFF_5814_0606,27.851854,93.688522,3,Female,25-34,VE,VENETO,"Master's Degree: Economics for arts, culture a...",Subordinate employment,Administrative Assistant,Finance / Accounting,TV

...Checking for duplicates in both dataframes

It makes sense to define what constitutes a duplicate in each dataframe. In this case:
- for the direct matching, we need to check if for each job_id we have the same candidate twice (because the dataframe represents, for each job, the 10 best candidates)
- for the inverse matching instead we have for each candidate the best job, therefore it makes sense to check if for the same candidate the same job is repeated multiple times

In [39]:
print(dm_df.duplicated(subset=['job_id', 'cand_id']).sum())
print(rm_df.duplicated(subset=['cand_id', 'job_id']).sum())

0
0

There are no duplicates defined as above in either of the dataframes, therefore there is no action ot do

...Checking for null values in both dataframes

In [36]:
numna_dm = dm_df.isna().sum().sum()
numna_rm = rm_df.isna().sum().sum()
print(f'Total number of null values in direct matching dataframe is {numna_dm}')
print(f'Total number of null values in reverse matching dataframe is {numna_rm}')

Total number of null values in direct matching dataframe is 6314
Total number of null values in reverse matching dataframe is 150729

Handling missing values by dropping them

In [37]:
dm_df = dm_df.dropna()